baseURL: "https://jamesgoldie.dev/"
languageCode: "en-us"
title: "James Goldie"
author:
  name: "James Goldie"
theme: "pathfinder"
taxonomies:
  tag: "tags"
  catgeory: "categories"

enableSharingButtons: true

markup:
  goldmark:
    renderer:
      unsafe: true

# metadata mostly used in document's head
description: "My new homepage or blog"
keywords: "homepage, blog"
# images = [""]

menu:
  main:
    - name: "Career"
      url: "/career"
    - name: "Projects"
      url: "/projects"
    - name: "Writing"
      url: "/writing"
    - name: "#"
      url: "/tags"

params:
  homeSubtitle: "I work to [visualise climate change](/career) and [build things for fun and social change](/projects) ðŸ¥³"
  Logo:
    logoText: "James Goldie"
  defaultTheme: "light"
  Portrait:
    Path: /images/james-2020-sm.jpg
  social:
    - name: twitter
      url: https://twitter.com/rensa_co
    - name: linkedin
      url: https://www.linkedin.com/in/jamesgoldie/
    - name: github
      url: https://github.com/rensa
    - name: gitlab
      url: https://gitlab.com/rensa
    - name: googlescholar
      url: https://scholar.google.com/citations?user=Otq-xj0AAAAJ&hl=en
    - name: keybase
      url: https://keybase.io/rensa
    - name: email
      url: mailto:me@jamesgoldie.dev
  # footerLeft: ""
  footerRight: ""
  related:
    includeNewer: true
    threshold: 80
    toLower: false
    indices:
      - name: seealso
        weight: 100
      - name: keywords
        weight: 10
      - name: date
        weight: 1